version: '3.8'

services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: base_clientes
      MYSQL_PASSWORD: root
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-conf:/etc/mysql/conf.d
      - ./mysql-init:/docker-entrypoint-initdb.d
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  backend:
    build: ./backend
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: base_clientes
      DB_PORT: 3306
    ports:
      - "3001:3000"
    volumes:
      - ./backend:/app
    command: node index.js

volumes:
  mysql_data: